root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/app ./main.go"
  bin = "tmp/app"
  full_bin = "APP_ENV=dev APP_USER=air ./tmp/app"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  log = "air.log"

[log]
  time = true

[misc]
  clean_on_exit = true
